export const Permissions = {
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  ROLE_READ: 'ROLE_READ',
  ROLE_MANAGE: 'ROLE_MANAGE',
  PERMISSION_READ: 'PERMISSION_READ',
  PERMISSION_MANAGE: 'PERMISSION_MANAGE',
} as const
